name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}  # Private key of EC2 KeyPair (for ED25519 don't forget add '\n' at the end)
      REMOTE_HOST: ${{ secrets.HOST_DNS }}         # EC2 Instance Public IPv4 address
      REMOTE_USER: ${{ secrets.USERNAME }}         # Ubuntu user, by default "ubuntu"
      TARGET: ${{ secrets.TARGET_DIR }}            # Directory for application on Ubuntu server on ubuntu (~/app)

    steps:
      - uses: actions/checkout@v3
      - uses: easingthemes/ssh-deploy@v3.1.0
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            sudo docker compose up --build -d