name: Publish Docker

on:
  push:
    branches: [master]


steps:
  - uses: actions/checkout@v3
  - uses: isbang/compose-action@v1.4.0
    with:
      compose-file: "./docker-compose.yml"
    env:
      CUSTOM_VARIABLE: "test"
